development:
  api_key: ENV['CLOUDINARY_API_KEY']
  api_secret: ENV['CLOUDINARY_API_SECRET']
  enhance_image_tag: 'true'
  static_file_support: 'true'
production:
 api_key: ENV['CLOUDINARY_API_KEY']
 api_secret: ENV['CLOUDINARY_API_SECRET']
 enhance_image_tag: 'true'
 static_file_support: 'true'